# Generated by Django 5.0 on 2025-01-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ward",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
