# Generated by Django 5.0 on 2024-02-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("pi", "Principal Investigator"),
                    ("co_pi", "Co-Principal Investigator"),
                    ("collaborator", "Collaborator"),
                ],
                max_length=20,
            ),
        ),
    ]
