# Generated by Django 5.0 on 2024-05-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "ADMIN"),
                    ("pi", "PI"),
                    ("co_pi", "Co-PI"),
                    ("normal", "NORMAL"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="status",
            field=models.IntegerField(default=1),
        ),
    ]
