# Generated by Django 5.0 on 2025-01-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_is_verified_user_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_code",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
