# Generated by Django 5.0 on 2024-11-21 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beans", "0002_alter_beansdata_uploaded_by"),
        ("cassava", "0002_alter_cassavadata_uploaded_by"),
        ("maize", "0002_alter_maizedata_uploaded_by"),
        ("news", "0002_alter_news_publisher"),
        ("rice", "0002_alter_ricedata_uploaded_by"),
        ("users", "0004_remove_userprofile_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
