# Generated by Django 5.0 on 2024-11-21 21:17

import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_delete_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platformuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(
            model_name="platformuser",
            name="date_registered",
        ),
        migrations.RemoveField(
            model_name="platformuser",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="platformuser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="platformuser",
            name="status",
        ),
        migrations.RemoveField(
            model_name="platformuser",
            name="street",
        ),
        migrations.RemoveField(
            model_name="platformuser",
            name="ward",
        ),
        migrations.AddField(
            model_name="platformuser",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_groups",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+255XXXXXXXXX'",
                        regex="^\\+255[0-9]{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_permissions",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterModelTable(
            name="platformuser",
            table="users",
        ),
    ]
