# Generated by Django 4.2.18 on 2025-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("agrovet", "Agrovet"),
                    ("normal", "Normal"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
