# Generated by Django 5.0 on 2024-11-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_platformuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("admin", "Admin"),
                    ("co_pi", "Co-Principal Investigator"),
                    ("pi", "Principal Investigator"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
