# Generated by Django 4.2.18 on 2025-02-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
