# Generated by Django 5.0 on 2024-11-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_platformuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("normal", "normal"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
