# Generated by Django 5.0 on 2024-07-15 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cassava", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cassavadata",
            old_name="image_id",
            new_name="file_id",
        ),
        migrations.RenameField(
            model_name="cassavadata",
            old_name="image_name",
            new_name="file_name",
        ),
        migrations.RenameField(
            model_name="cassavadata",
            old_name="image_path",
            new_name="file_path",
        ),
    ]
