# Generated by Django 5.0 on 2024-11-30 02:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cassava", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CassavaDataData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=100)),
                ("file_path", models.FileField(max_length=200, upload_to="files")),
                ("file_name", models.CharField(max_length=100)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CassavaDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_id", models.CharField(max_length=100, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="cassava_detections")),
                (
                    "output_path",
                    models.FileField(upload_to="cassava_detection_outputs"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "detection_results",
                    models.JSONField(
                        help_text="Detailed detection results including classes and counts"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cassava_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CassavaPredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_id", models.CharField(max_length=100, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="cassava_predictions")),
                (
                    "predicted_disease",
                    models.CharField(
                        choices=[
                            ("Bacterial Blight", "Bacterial Blight"),
                            ("Brown Spot", "Brown Spot"),
                            ("Browm Steak", "Browm Steak"),
                            ("Green Mottle", "Green Mottle"),
                            ("Healthy", "Healthy"),
                            ("Mosaic Desease", "Mosaic Desease"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                (
                    "probabilities",
                    models.JSONField(
                        help_text="Detailed probabilities for each disease class"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cassava_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
