# Generated by Django 5.0 on 2024-07-16 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cassava", "0002_rename_image_id_cassavadata_file_id_and_more"),
        ("users", "0003_alter_userprofile_role_alter_userprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cassavadata",
            name="uploaded_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.userprofile",
            ),
            preserve_default=False,
        ),
    ]
