# Generated by Django 5.0 on 2024-02-23 23:06

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="PNG",
                keep_meta=True,
                quality=100,
                scale=0.5,
                size=[1140, 760],
                upload_to="news",
            ),
        ),
    ]
