# Generated by Django 5.0 on 2024-05-15 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_remove_news_file"),
        ("users", "0003_alter_userprofile_role_alter_userprofile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="description",
        ),
        migrations.RemoveField(
            model_name="news",
            name="header_image",
        ),
        migrations.AlterField(
            model_name="news",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
    ]
