# Generated by Django 5.0 on 2024-02-23 23:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beansdata",
            old_name="filename",
            new_name="image_name",
        ),
        migrations.RenameField(
            model_name="beansdata",
            old_name="filepaths",
            new_name="image_path",
        ),
    ]
