# Generated by Django 5.0 on 2024-11-30 02:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeansDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_id", models.CharField(max_length=100, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="beans_detections")),
                ("output_path", models.FileField(upload_to="beans_detection_outputs")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "detection_results",
                    models.JSONField(
                        help_text="Detailed detection results including classes and counts"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beans_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeansPredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_id", models.CharField(max_length=100, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="beans_predictions")),
                (
                    "predicted_disease",
                    models.CharField(
                        choices=[
                            ("Angular Leaf Spot", "Angular Leaf Spot"),
                            ("Anthracnose", "Anthracnose"),
                            ("Ascochyta Leaf Spot", "Ascochyta Leaf Spot"),
                            ("Common Bacterial Blight", "Common Bacterial Blight"),
                            ("Common Mosaic Rust", "Common Mosaic Rust"),
                            ("Bean Rust", "Bean Rust"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                (
                    "probabilities",
                    models.JSONField(
                        help_text="Detailed probabilities for each disease class"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beans_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
