# Generated by Django 5.0 on 2024-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beans", "0002_rename_filename_beansdata_image_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beansdata",
            name="image_path",
            field=models.FileField(max_length=200, upload_to="files"),
        ),
    ]
