# Generated by Django 5.0 on 2024-11-21 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rice", "0001_initial"),
        ("users", "0004_remove_userprofile_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricedata",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.platformuser"
            ),
        ),
    ]
