# Generated by Django 5.0 on 2024-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricedata",
            name="image_path",
            field=models.FileField(max_length=200, upload_to="files"),
        ),
    ]
