# Generated by Django 4.1.6 on 2024-04-27 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmotionsData",
            new_name="RainData",
        ),
    ]
