# Generated by Django 5.0 on 2024-05-25 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maize", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maizedata",
            old_name="image_id",
            new_name="file_id",
        ),
        migrations.RenameField(
            model_name="maizedata",
            old_name="image_name",
            new_name="file_name",
        ),
        migrations.RemoveField(
            model_name="maizedata",
            name="image_path",
        ),
        migrations.AddField(
            model_name="maizedata",
            name="file_path",
            field=models.FileField(
                default=django.utils.timezone.now, max_length=200, upload_to="files"
            ),
            preserve_default=False,
        ),
    ]
