# Generated by Django 5.0 on 2024-11-29 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maize", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaizeDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="maize_detections/")),
                ("output_path", models.FileField(upload_to="maize_detection_outputs/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "detection_results",
                    models.JSONField(
                        help_text="Detailed detection results including classes and counts"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maize_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaizePredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="maize_predictions/")),
                (
                    "predicted_disease",
                    models.CharField(
                        choices=[
                            ("Common Rust", "Common Rust"),
                            ("Fally Army Worm", "Fally Army Worm"),
                            ("Gray Leaf Spot", "Gray Leaf Spot"),
                            ("Healthy", "Healthy"),
                            ("Leaf Blight", "Leaf Blight"),
                            ("Lethal Necrosis", "Lethal Necrosis"),
                            ("Pysoderma Leaf Spot", "Pysoderma Leaf Spot"),
                            ("Streak Virus", "Streak Virus"),
                            ("Undetermined", "Undetermined"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                (
                    "probabilities",
                    models.JSONField(
                        help_text="Detailed probabilities for each disease class"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maize_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
