# Generated by Django 5.0 on 2024-11-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maize", "0004_remove_maizedata_result_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maizedetectionresult",
            name="file_path",
            field=models.FileField(upload_to="maize_detections"),
        ),
        migrations.AlterField(
            model_name="maizedetectionresult",
            name="output_path",
            field=models.FileField(upload_to="maize_detection_outputs"),
        ),
        migrations.AlterField(
            model_name="maizepredictionresult",
            name="file_path",
            field=models.FileField(upload_to="maize_predictions"),
        ),
    ]
