# Generated by Django 5.0 on 2025-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maize", "0005_alter_maizedetectionresult_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maizedata",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="maizedata",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="maizedata",
            name="full_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maizedata",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="maizedata",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="maizedata",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
